### ISSUE TITLE
Barrels and Sieves out of different Woods

### ISSUE THREAD

**Issue by BedrockLegends** [NovaMachina-Mods/ExNihiloSequentia#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to see Barrels and Sieves made out of different types of wood, then just the Oak one

**Comment by CreatorVilius** [comment]
I guess like og Ex Nihilo did.

**Comment by Blackout03** [comment]
this

**Comment by ToMe25** [comment]
I, too, support this suggestion.

While on the topic of different wood types support i would also like to suggest Wooden Crucibles made from different wood types, like the Ex Nihilo Omnia ones.

Also while the original Ex Nihilo seems to have had barrels and sieves made from different wood types,
neither did Ex Nihilo Adscensio, nor Ex Nihilo Creatio for forge on which Ex Nihilo Sequentia is based had them.
Ex Nihilo Creatio for fabric seems to have had different wood type barrels and sieves however.

The only Ex Nihilo forge fork that had different types of barrels and sieves seems to have been Ex Nihilo Omnia, which also had glass and colored glass barrels.

I would also like to suggest supporting the two new nether wood types as well, now that they exist.
